apiVersion: v1
kind: Service
metadata:
  labels:
    run: envoy-simple
  name: envoy-simple
  namespace: default
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: envoy-simple
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
